name: Build Ubuntu

on:
  pull_request:
    paths:
      - 'medhand/**'
      - 'requirements.txt'
      - 'compilation/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Ubuntu
      run: |
        ./compilation/compile_ubuntu.sh

    - name: Upload Ubuntu artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu_artifact.zip
        path: target/target_ubuntu.zip
        retention-days: 7
